# Generated by Django 4.0.2 on 2022-04-11 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjimon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sherlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('matn', models.TextField()),
                ('vaqt', models.DateField()),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author')),
            ],
            options={
                'ordering': ['-vaqt'],
            },
        ),
        migrations.CreateModel(
            name='Maqolalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('matn', models.TextField()),
                ('vaqt', models.DateField()),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author')),
            ],
            options={
                'ordering': ['-vaqt'],
            },
        ),
        migrations.CreateModel(
            name='LirikTarjima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('matn', models.TextField()),
                ('vaqt', models.DateField()),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author')),
                ('tarjimon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tarjimon')),
            ],
            options={
                'ordering': ['-vaqt'],
            },
        ),
        migrations.CreateModel(
            name='Lavhalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('matn', models.TextField()),
                ('vaqt', models.DateField()),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author')),
            ],
            options={
                'ordering': ['-vaqt'],
            },
        ),
        migrations.CreateModel(
            name='Hikoyalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('matn', models.TextField()),
                ('vaqt', models.DateField()),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author')),
            ],
            options={
                'ordering': ['-vaqt'],
            },
        ),
        migrations.CreateModel(
            name='Etyudlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('matn', models.TextField()),
                ('vaqt', models.DateField()),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author')),
            ],
            options={
                'ordering': ['-vaqt'],
            },
        ),
        migrations.CreateModel(
            name='EpikTarjima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('matn', models.TextField()),
                ('vaqt', models.DateField()),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author')),
                ('tarjimon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tarjimon')),
            ],
            options={
                'ordering': ['-vaqt'],
            },
        ),
        migrations.CreateModel(
            name='DramatikTarjima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('matn', models.TextField()),
                ('vaqt', models.DateField()),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author')),
                ('tarjimon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tarjimon')),
            ],
            options={
                'ordering': ['-vaqt'],
            },
        ),
    ]
