# Generated by Django 4.0.4 on 2022-04-15 04:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dramatiktarjima',
            name='matn',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='epiktarjima',
            name='matn',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='etyudlar',
            name='matn',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='hikoyalar',
            name='matn',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='lavhalar',
            name='matn',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='liriktarjima',
            name='matn',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='maqolalar',
            name='matn',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='sherlar',
            name='matn',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
